Vagrant.configure("2") do |config|
    config.vm.box = "centos/8"
    config.vm.define "wso2mi" do |wso2mi|
	wso2mi.vm.hostname = "wso2mi"

	wso2mi.vm.provider "virtualbox" do |vb|
	    vb.name = "t2b WSO2 micro integrator"
	    vb.memory = "4096"
	    vb.cpus = "2"
	    vb.gui = false
	end
    config.vbguest.installer_options = { allow_kernel_upgrade: true }

	# https://www.vagrantup.com/docs/providers/virtualbox/networking
    config.vm.network "private_network", type: "dhcp", virtualbox__intnet: true

	config.vm.synced_folder "~/vagrant_data", "/vagrant_data"

	config.vm.provision "basicUtilities",    type: "shell", path: "../Provisioning/basicUtilities.sh"
	config.vm.provision "oracleJDK",         type: "shell", path: "../Provisioning/oracleJDK.sh"
    config.vm.provision "shell" do |s|
        s.path = "../Provisioning/wso2-product-dist.sh"
        s.args   = ["micro-integrator", "4.0.0", "wso2mi"]
    end
  
	config.vm.provision "shell", inline: <<-SHELL
        echo "****** REBOOTING... ******"
	    reboot
	SHELL
    end
end
