Vagrant.configure("2") do |config|
    config.vm.define "wso2am" do |wso2am|
		wso2am.vm.box = "centos/8"
		wso2am.vm.hostname = "wso2am"
		wso2am.vm.provider "virtualbox" do |vb|
			vb.name = "t2b WSO2 API Manager (9443)"
			vb.memory = "4096"
			vb.cpus = "2"
			vb.gui = false
		end

		wso2am.vm.network "forwarded_port", guest: 9443, host: 9443
		wso2am.vm.network "private_network", ip: "192.168.56.11"
		wso2am.vm.synced_folder "~/vagrant_data", "/vagrant_data"

		wso2am.vm.provision "basicUtils",		type: "shell",	path: "../Provisioning/basicUtilities.sh"
		wso2am.vm.provision "jdk",				type: "shell",	path: "../Provisioning/oracleJDK.sh"
		#wso2am.vm.provision "rtail",			type: "shell",	path: "../Provisioning/rtail.sh"
		wso2am.vm.provision "download-api-manager", type: "shell",
			path: "../Provisioning/wso2-product-dist.sh",
			args: ["https://product-dist.wso2.com/products/api-manager/4.0.0/wso2am-4.0.0.zip"]

		wso2am.vm.provision "apictl",			type: "shell",	path: "../Provisioning/apictl.sh"
		wso2am.vm.provision "maven",			type: "shell",	path: "../Provisioning/maven.sh"
		wso2am.vm.provision "pizza",			type: "shell",	path: "../Provisioning/pizzaShack.sh"
		wso2am.vm.provision "systemd-service",	type: "shell",	path: "../Provisioning/systemd-service.sh",
			args: ["/opt/wso2/wso2am/bin/api-manager.sh"]

		wso2am.vm.provision "t2bTraining",		type: "shell", path: "t2bTraining.sh"
	end
end
