Vagrant.configure("2") do |config|
    config.vm.define "wso2am" do |wso2am|
	wso2am.vm.box = "centos/8"
	wso2am.vm.hostname = "wso2am"
	wso2am.vm.provider "virtualbox" do |vb|
	    vb.name = "t2b WSO2 API Manager 1 (9443)"
	    vb.memory = "4096"
	    vb.cpus = "2"
	    vb.gui = false
	end

	config.vm.network "forwarded_port", guest: 9443, host: 9443
	config.vm.network "forwarded_port", guest: 8243, host: 8243
	config.vm.network "forwarded_port", guest: 8244, host: 8244
	config.vm.network "forwarded_port", guest: 8889, host: 8889
	config.vm.network "private_network", ip: "192.168.56.11"
	
	config.vbguest.installer_options = { allow_kernel_upgrade: true }
	config.vm.synced_folder "~/vagrant_data", "/vagrant_data"	

	config.vm.provision "basicUtils",		type: "shell",	path: "../Provisioning/basicUtilities.sh"
	config.vm.provision "jdk",				type: "shell",	path: "../Provisioning/oracleJDK.sh"
	config.vm.provision "rtail",			type: "shell",	path: "../Provisioning/rtail.sh"
	config.vm.provision "download-api-manager", type: "shell",
			path: "../Provisioning/wso2-product-dist.sh",
			args: ["https://product-dist.wso2.com/products/api-manager/4.0.0/wso2am-4.0.0.zip"]

	config.vm.provision "apictl",			type: "shell",	path: "../Provisioning/apictl.sh"
	config.vm.provision "maven",			type: "shell",	path: "../Provisioning/maven.sh"
	config.vm.provision "pizza",			type: "shell",	path: "../Provisioning/pizzaShack.sh"
	
	config.vm.provision "systemd-svc-api-m",type: "shell",	path: "../Provisioning/systemd-service.sh",
		args: ["/opt/wso2/wso2am/bin/api-manager.sh"]
	config.vm.provision "systemd-svc-rtail",type: "shell",	path: "../Provisioning/systemd-service.sh",
		args: ["/opt/rtail/start-rtail.sh"]
	config.vm.provision "systemd-svc-rtail-apim",type: "shell",	path: "../Provisioning/systemd-service.sh",
		args: ["/opt/rtail/rtail-wso2am.sh"]

	config.vm.provision "t2bTraining",		type: "shell", path: "t2bTraining.sh"
	
	config.vm.provision "test",				type: "shell", path: "TestScript.sh"
    end
end
