Vagrant.configure("2") do |config|
	config.vm.box = "centos/8"
	config.vm.define "box" do |box|
		box.vm.hostname = "wso2box"
		box.vm.provider "virtualbox" do |vb|
			vb.name = "centos-t2b"
			vb.memory = "1024"
			vb.cpus = "2"
			vb.gui = false
		end
		config.vbguest.installer_options = { allow_kernel_upgrade: true }
		config.vm.synced_folder "~/vagrant_data", "/vagrant_data"
		config.vm.provision "basicUtilities",    type: "shell", path: "../Provisioning/basicUtilities.sh"
		config.vm.provision "oracleJDK",         type: "shell", path: "../Provisioning/oracleJDK.sh"
		config.vm.provision "shell", inline: <<-SHELL
			echo "****** REBOOTING... ******"
			reboot
		SHELL
	end
end
