Vagrant.configure("2") do |config|
	config.vm.define "wso2ei", primary: true do |host|

		# Basic VM configuration
		host.vm.box = "centos/7"
		host.vm.hostname = "wso2ei"
		host.vm.provider "virtualbox" do |vb|
			vb.name = "t2b WSO2 Enterprise Integrator (9443)"
			vb.memory = "4096"
			vb.cpus = "2"
			vb.gui = false
		end
		
		# Network configuration
		host.vm.network "private_network", ip: "192.168.56.14"

		# Special virtualbox configuration
		host.vbguest.installer_options = { allow_kernel_upgrade: true }
		host.vm.synced_folder "~/vagrant_data", "/vagrant_data"
		
		# Provisioning: system software and tools installation
		host.vm.provision "basicUtilities",    type: "shell", path: "../Provisioning/basicUtilities.sh"
		host.vm.provision "oracleJDK",         type: "shell", path: "../Provisioning/oracleJDK.sh"

		# Provisioning: services needed to automatically start WSO2 and associated tools
		host.vm.provision "product-dist-ent-integrator", type: "shell", 
			path: "../Provisioning/wso2-product-dist.sh",
			args: ["https://product-dist.wso2.com/products/enterprise-integrator/6.6.0/wso2ei-6.6.0.zip"]
		host.vm.provision "ent-home", type: "shell",
			inline: "echo 'export EI_HOME=/opt/wso2/wso2ei' | sudo tee -a /etc/profile.d/envvars.sh"
		host.vm.provision "systemd-service-enterprise-integrator", type: "shell", 
			path: "../Provisioning/systemd-service.sh",
			args: ["/opt/wso2/wso2ei/bin/integrator.sh"]

		# Provisioning: custom provisioning of this virtual machine
		host.vm.provision "configure", type: "shell", path: "configure.sh"

		# Provisioning: the first time that a new Virtual Machine is created, we force a reboot, just to be sure
		host.vm.provision "shell", inline: <<-SHELL
			echo "****** REBOOTING... ******"
			reboot
		SHELL
	end
end
